// Generated by Wrangler on Sat Jul 20 2024 21:58:18 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	ATLAS_APP_ID: string;
	ATLAS_API_KEY: string;
	HASHIDS_SALT: string;
}
